import type { Metadata } from "next";
import { Dancing_Script } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import LeftSideBar from "@/components/left-side-bar";
import NavContextProver from "@/components/nav-provider";

const inter = Dancing_Script({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-hidden px-8 py-4 bg-background w-full`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NavContextProver>
            <Header />
            <LeftSideBar />
            <main className="">{children}</main>
          </NavContextProver>
        </ThemeProvider>
      </body>
    </html>
  );
}
